# Generated by Django 5.1.3 on 2024-11-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Base address', 'verbose_name_plural': 'Base addresses'},
        ),
        migrations.AlterModelOptions(
            name='addresslines',
            options={'verbose_name': 'Address lines', 'verbose_name_plural': 'Address lines'},
        ),
    ]
